version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dockerfiles/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./dockerdata/mysql:/var/lib/mysql

  drupal:
    depends_on:
      - mysql
    image: drupal:latest
    links:
      - mysql
    ports:
      - "8000:80"
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    links:
      - mysql
    ports:
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

  ghost:
    image: ghost:latest
    ports:
      - "8002:2368"
    restart: always
    volumes:
      - ./dockerdata/ghost:/var/lib/ghost

  wagtail:
    depends_on:
      - mysql
    build:
      context: dockerfiles/wagtail
    links:
      - mysql
    ports:
      - "8003:8080"
    restart: always
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/wagtail
      SECRET_KEY: mysecretkey
    volumes:
      - ./dockerdata/wagtail:/public/
